name: baitstick-analysis

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy>=1.24
  - opencv-python
  - pandas>=2.1
  - pillow>=10.0
  - tqdm>=4.66
  - pip
  - pip:
      - openpyxl
